AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Custom Contact Center - Serverless Backend

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: ContactCenter
        AWS_ENDPOINT: http://host.docker.internal:4566

Resources:

  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PingFunction
      CodeUri: ../backend
      Handler: dist/handlers/ping.handler   # ✅ compiled JS output
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /ping
            Method: get

Outputs:

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "http://localhost:3000"